#!/usr/bin/python3
""" Class factor_file """
from sys import argv
from math import sqrt


class factor_file:
    """ init """
    def __init__(self, filename):
        """check if
        file is not NULL
        """
        if filename is not None:
            self.filename = filename

    def open_read_file(self):
        """read from file
        add to array
        """
        with open(self.filename, encoding="utf-8") as file:
            lines = file.readlines()
        number_to_factor = []
        for line in lines:
            number_to_factor.append(int(line))
        return number_to_factor

    def factorial(self, n):
        """factor each
        n given
        """
        result = []
        i = 1
        m = n
        if n > 239809320265259:
            m = round(sqrt(n))
        while i * i <= m:
            if n % i == 0:
                result.append(i)
                if n // i != i:
                    result.append((n // i))
            i += 1
        if len(result) == 3:
            print("{}={}*{}".format(result[1], result[2], result[2]))
            return result
        print("{}={}*{}".format(result[1], result[3], result[2]))
        return result

    def factor_each_n_in_lis(self):
        """factor each
        num in ls
        """
        ls = self.open_read_file()
        for n in ls:
            self.factorial(n)


if (len(argv) == 2):
    factor_file(argv[1]).factor_each_n_in_lis()
