#!/usr/bin/python3
""" Class factor_file """
from sys import argv
from math import sqrt


class factor_file:
    """ init """
    def __init__(self, filename):
        """check if
        file is not NULL
        """
        if filename is not None:
            self.filename = filename

    def open_read_file(self):
        """read from file
        add to array
        """
        with open(self.filename, encoding="utf-8") as file:
            lines = file.readlines()
        number_to_factor = []
        for line in lines:
            number_to_factor.append(int(line))
        return number_to_factor

    def is_prime(self, n):
        if n > 1:
            for i in range(2, n):
                if (n % i) == 0:
                    return False
        return True

    def factorial(self, n):
        """factor each
        n given
        """
        is_p = self.is_prime(n)
        if is_p:
            print("{}={}*{}".format(n, n, 1))
            return True
        while (is_p is False):
            for i in range(2, n):
                if n == ((n // i) * i):
                    print("{}={}*{}".format(n, (n // i), i))
                    return False

    def factor_each_n_in_lis(self):
        """factor each
        num in ls
        """
        ls = self.open_read_file()
        for n in ls:
            self.factorial(n)


for i in range(1, len(argv)):
    factor_file(argv[i]).factor_each_n_in_lis()
